version: '3.2'

services:
  oauth:
    build:
      context: ./oauth
      dockerfile: compose/Dockerfile
    env_file: .env
    image: oauth
    container_name: oauth
    restart: always
    ports:
      - 6000:80
